version: 0.0
os: linux
files:
    - source: /
      destination: /home/ec2-user/
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
  ApplicationStop::
    - location: scripts/stop.sh
      timeout: 300

